# Generated by Django 2.0.5 on 2018-05-18 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionlab', models.CharField(max_length=999)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='available_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='career',
            field=models.CharField(blank=True, max_length=99),
        ),
        migrations.AddField(
            model_name='course',
            name='class_notes',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AddField(
            model_name='course',
            name='class_num',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.CharField(blank=True, max_length=99),
        ),
        migrations.AddField(
            model_name='course',
            name='days_and_times',
            field=models.CharField(blank=True, max_length=99),
        ),
        migrations.AddField(
            model_name='course',
            name='enrolled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='enrollment_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='general_education',
            field=models.CharField(blank=True, max_length=99),
        ),
        migrations.AddField(
            model_name='course',
            name='grading',
            field=models.CharField(blank=True, max_length=99),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.CharField(blank=True, max_length=99),
        ),
        migrations.AddField(
            model_name='course',
            name='meeting_dates',
            field=models.CharField(blank=True, max_length=99),
        ),
        migrations.AddField(
            model_name='course',
            name='room',
            field=models.CharField(blank=True, max_length=99),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(blank=True, max_length=99),
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(blank=True, max_length=99),
        ),
        migrations.AddField(
            model_name='course',
            name='waitlist_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='waitlist_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='section_and_labs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.SectionLab'),
        ),
    ]
