# Generated by Django 2.0.5 on 2018-05-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180519_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionlab',
            name='course_num',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
