# Generated by Django 2.0.5 on 2018-05-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='subject',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='review',
            name='term',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
